creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: ^(kind)$
    key_groups:
      - age:
          - age1fxzzc3yyc9qn4d8pyztkyw2vjckvrv75lsmv0ff274t2z3s55vnqfxy6ap
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - age1fxzzc3yyc9qn4d8pyztkyw2vjckvrv75lsmv0ff274t2z3s55vnqfxy6ap
