kubernetes:
  children:
    master:
      hosts:
        raspberrypi4b8gb:
          ansible_host: 10.0.1.10
    worker:
      hosts:
        raspberrypi4b4gb:
          ansible_host: 10.0.1.11
        raspberrypi3bplus:
          ansible_host: 10.0.1.12
