---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Asia/Tokyo
  METALLB_LB_RANGE: 10.0.2.1-10.0.2.254
  METALLB_K8S_GATEWAY_ADDR: 10.0.2.1
  METALLB_TRAEFIK_ADDR: 10.0.2.2
