# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4CrYrxIQ04d9F0B0X8anXWhw4GMJv/WW8ECH/sZkupBzr739iGfq9w==,iv:SE8yoYkN54PCrA6kVZg8TVsLl7+ybPfR7PwCsPw8VIc=,tag:GxNIMzvfK0i6ZKZi2c9otw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxzzc3yyc9qn4d8pyztkyw2vjckvrv75lsmv0ff274t2z3s55vnqfxy6ap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UE1Tb20yS0cxNTBnTVhi
            K3hkZFhmZU00eDQ0QW9OK3Y3SzkrSk9BK2lVClBsWGx5QzZMZWY1K2FZaUhmY2o4
            cEtmanBMNUUyVG5EWlNiUUtwYjlpTlUKLS0tIElXcTVUVXNDTkY2RmZaTVFUS09t
            VVMxc0NvbGd3TWZ4NHpwcDlXSk9tUk0K9St3bBWCREL0gMTO+GVPcrkpwAqMcFlW
            tqiu0y+mSzWueddv0jMrOG4iDRP+HZdAyZFtfPapTbCris88nRqM7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T10:23:08Z"
    mac: ENC[AES256_GCM,data:2f5Vhd1wPKg2Rb1JuMlMF0s6LzPOT0MA0P4WTvdym7zQzSrqQd/3ziuoohDvuzrxK5ExUwzFR+xXT8FpHYR+KM7qRJUAxFpmMtlYPr+q8B2/PrqZlMyOCLialTcl64514hRcgmQ9fs28uOUd31rUwzbnJjv4/GpfjWPpJhuGJEc=,iv:LkBtIg7EHSeNJj0w7F/cd2gKdfxjdBRuUKAd6+SKYzw=,tag:05yYjTBHf4e5Xos2s+z3kQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
